"""Shared data contracts for handler inputs and outputs."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Scene schema — used by storyboard output and worker input injection
# ---------------------------------------------------------------------------

class Scene(BaseModel):
    """Represents a single scene generated by the storyboard node.

    Attributes:
        scene_id: Unique scene identifier (e.g. "scene-001", "scene-002").
        index: Zero-based position in the storyboard sequence.
        narration: Narration / description text for this scene.
        image_prompt: Prompt to feed into a text-to-image model.
        video_prompt: Prompt to feed into an image-to-video model.
        duration: Desired duration in seconds (accepts ``duration_seconds`` from
            storyboard output via validation alias).
        metadata: Arbitrary extra data (style hints, camera tags, etc.).
    """

    model_config = ConfigDict(populate_by_name=True)

    scene_id: str
    index: int
    narration: str = ""
    image_prompt: str = ""
    video_prompt: str = ""
    duration: float = Field(default=5.0, validation_alias="duration_seconds")
    metadata: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Error schema
# ---------------------------------------------------------------------------

class NodeError(BaseModel):
    """Structured error information returned by a handler."""

    code: str
    message: str
    retryable: bool = False
    details: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Artifact reference schema
# ---------------------------------------------------------------------------

class ArtifactRef(BaseModel):
    """Reference to a generated asset (image, video, text, audio)."""

    type: Literal["image", "video", "text", "audio"]
    asset_id: str | None = None
    scene_id: str | None = None
    url: str | None = None
    metadata: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Node result schema
# ---------------------------------------------------------------------------

class NodeResult(BaseModel):
    """Standard result returned by every NodeHandler.execute()."""

    status: Literal["succeeded", "failed"]
    output: ArtifactRef | None = None
    artifacts: list[str] = Field(default_factory=list)
    metrics: dict = Field(default_factory=dict)
    error: NodeError | None = None

    # -- convenience helpers ---------------------------------------------------

    @classmethod
    def ok(cls, output: ArtifactRef | None = None, **kwargs) -> NodeResult:
        """Shorthand for a successful result."""
        return cls(status="succeeded", output=output, **kwargs)

    @classmethod
    def fail(
        cls,
        code: str = "UNKNOWN",
        message: str = "",
        retryable: bool = False,
        details: dict | None = None,
    ) -> NodeResult:
        """Shorthand for a failed result."""
        return cls(
            status="failed",
            error=NodeError(
                code=code,
                message=message,
                retryable=retryable,
                details=details or {},
            ),
        )

    def to_dict(self) -> dict:
        """Serialize to a plain dict suitable for JSON storage."""
        return self.model_dump(exclude_none=True)
